--
-- PostgreSQL database dump
--

\restrict 1vy5UC3Vcvz5wV9C3j4FNb4Lya5g3v9ZCmJpchARn59NfYtHlZjH1qSE1Kf7Kfc

-- Dumped from database version 17.6
-- Dumped by pg_dump version 17.6 (Ubuntu 17.6-2.pgdg24.04+1)

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

--
-- Name: common; Type: SCHEMA; Schema: -; Owner: -
--

CREATE SCHEMA common;


SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: atch_file; Type: TABLE; Schema: common; Owner: -
--

CREATE TABLE common.atch_file (
    atch_file_id integer NOT NULL,
    file_grp_code_id integer,
    created_id integer,
    created_dt timestamp with time zone DEFAULT now(),
    updated_id integer,
    updated_dt timestamp with time zone DEFAULT now()
);


--
-- Name: TABLE atch_file; Type: COMMENT; Schema: common; Owner: -
--

COMMENT ON TABLE common.atch_file IS '첨부파일 묶음 테이블';


--
-- Name: COLUMN atch_file.atch_file_id; Type: COMMENT; Schema: common; Owner: -
--

COMMENT ON COLUMN common.atch_file.atch_file_id IS '첨부파일 PK';


--
-- Name: COLUMN atch_file.file_grp_code_id; Type: COMMENT; Schema: common; Owner: -
--

COMMENT ON COLUMN common.atch_file.file_grp_code_id IS '파일 그룹 코드 (공통코드 참조)';


--
-- Name: COLUMN atch_file.created_id; Type: COMMENT; Schema: common; Owner: -
--

COMMENT ON COLUMN common.atch_file.created_id IS '생성자 ID';


--
-- Name: COLUMN atch_file.created_dt; Type: COMMENT; Schema: common; Owner: -
--

COMMENT ON COLUMN common.atch_file.created_dt IS '생성일시';


--
-- Name: COLUMN atch_file.updated_id; Type: COMMENT; Schema: common; Owner: -
--

COMMENT ON COLUMN common.atch_file.updated_id IS '수정자 ID';


--
-- Name: COLUMN atch_file.updated_dt; Type: COMMENT; Schema: common; Owner: -
--

COMMENT ON COLUMN common.atch_file.updated_dt IS '수정일시';


--
-- Name: atch_file_atch_file_id_seq; Type: SEQUENCE; Schema: common; Owner: -
--

ALTER TABLE common.atch_file ALTER COLUMN atch_file_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME common.atch_file_atch_file_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: atch_file_item; Type: TABLE; Schema: common; Owner: -
--

CREATE TABLE common.atch_file_item (
    atch_file_item_id integer NOT NULL,
    atch_file_id integer NOT NULL,
    path character varying(400),
    file_name character varying(400),
    file_size integer,
    created_id integer,
    created_dt timestamp with time zone DEFAULT now(),
    updated_id integer,
    updated_dt timestamp with time zone DEFAULT now()
);


--
-- Name: TABLE atch_file_item; Type: COMMENT; Schema: common; Owner: -
--

COMMENT ON TABLE common.atch_file_item IS '첨부파일 개별 항목 테이블';


--
-- Name: COLUMN atch_file_item.atch_file_item_id; Type: COMMENT; Schema: common; Owner: -
--

COMMENT ON COLUMN common.atch_file_item.atch_file_item_id IS '첨부파일 항목 PK';


--
-- Name: COLUMN atch_file_item.atch_file_id; Type: COMMENT; Schema: common; Owner: -
--

COMMENT ON COLUMN common.atch_file_item.atch_file_id IS '첨부파일 PK 참조';


--
-- Name: COLUMN atch_file_item.path; Type: COMMENT; Schema: common; Owner: -
--

COMMENT ON COLUMN common.atch_file_item.path IS '파일 저장 경로';


--
-- Name: COLUMN atch_file_item.file_name; Type: COMMENT; Schema: common; Owner: -
--

COMMENT ON COLUMN common.atch_file_item.file_name IS '원본 파일명';


--
-- Name: COLUMN atch_file_item.file_size; Type: COMMENT; Schema: common; Owner: -
--

COMMENT ON COLUMN common.atch_file_item.file_size IS '파일 크기 (byte)';


--
-- Name: COLUMN atch_file_item.created_id; Type: COMMENT; Schema: common; Owner: -
--

COMMENT ON COLUMN common.atch_file_item.created_id IS '생성자 ID';


--
-- Name: COLUMN atch_file_item.created_dt; Type: COMMENT; Schema: common; Owner: -
--

COMMENT ON COLUMN common.atch_file_item.created_dt IS '생성일시';


--
-- Name: COLUMN atch_file_item.updated_id; Type: COMMENT; Schema: common; Owner: -
--

COMMENT ON COLUMN common.atch_file_item.updated_id IS '수정자 ID';


--
-- Name: COLUMN atch_file_item.updated_dt; Type: COMMENT; Schema: common; Owner: -
--

COMMENT ON COLUMN common.atch_file_item.updated_dt IS '수정일시';


--
-- Name: atch_file_item_atch_file_item_id_seq; Type: SEQUENCE; Schema: common; Owner: -
--

ALTER TABLE common.atch_file_item ALTER COLUMN atch_file_item_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME common.atch_file_item_atch_file_item_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: code; Type: TABLE; Schema: common; Owner: -
--

CREATE TABLE common.code (
    code_id integer NOT NULL,
    upper_code_id integer,
    code character varying(40) NOT NULL,
    code_name character varying(200),
    description character varying(4000),
    srt integer,
    etc1 character varying(100),
    etc2 character varying(100),
    etc3 character varying(100),
    etc4 character varying(100),
    use_yn boolean DEFAULT true,
    created_id integer,
    created_dt timestamp with time zone DEFAULT now(),
    updated_id integer,
    updated_dt timestamp with time zone DEFAULT now(),
    order_path character varying(1000)
);


--
-- Name: TABLE code; Type: COMMENT; Schema: common; Owner: -
--

COMMENT ON TABLE common.code IS '공통 코드 관리 테이블';


--
-- Name: COLUMN code.code_id; Type: COMMENT; Schema: common; Owner: -
--

COMMENT ON COLUMN common.code.code_id IS '코드 PK (Surrogate Key)';


--
-- Name: COLUMN code.upper_code_id; Type: COMMENT; Schema: common; Owner: -
--

COMMENT ON COLUMN common.code.upper_code_id IS '상위 코드 ID';


--
-- Name: COLUMN code.code; Type: COMMENT; Schema: common; Owner: -
--

COMMENT ON COLUMN common.code.code IS '코드 값 (논리 식별자)';


--
-- Name: COLUMN code.code_name; Type: COMMENT; Schema: common; Owner: -
--

COMMENT ON COLUMN common.code.code_name IS '코드명';


--
-- Name: COLUMN code.description; Type: COMMENT; Schema: common; Owner: -
--

COMMENT ON COLUMN common.code.description IS '코드 설명';


--
-- Name: COLUMN code.srt; Type: COMMENT; Schema: common; Owner: -
--

COMMENT ON COLUMN common.code.srt IS '정렬 순서';


--
-- Name: COLUMN code.etc1; Type: COMMENT; Schema: common; Owner: -
--

COMMENT ON COLUMN common.code.etc1 IS '예비 컬럼1';


--
-- Name: COLUMN code.etc2; Type: COMMENT; Schema: common; Owner: -
--

COMMENT ON COLUMN common.code.etc2 IS '예비 컬럼2';


--
-- Name: COLUMN code.etc3; Type: COMMENT; Schema: common; Owner: -
--

COMMENT ON COLUMN common.code.etc3 IS '예비 컬럼3';


--
-- Name: COLUMN code.etc4; Type: COMMENT; Schema: common; Owner: -
--

COMMENT ON COLUMN common.code.etc4 IS '예비 컬럼4';


--
-- Name: COLUMN code.use_yn; Type: COMMENT; Schema: common; Owner: -
--

COMMENT ON COLUMN common.code.use_yn IS '사용 여부';


--
-- Name: COLUMN code.created_id; Type: COMMENT; Schema: common; Owner: -
--

COMMENT ON COLUMN common.code.created_id IS '생성자 ID';


--
-- Name: COLUMN code.created_dt; Type: COMMENT; Schema: common; Owner: -
--

COMMENT ON COLUMN common.code.created_dt IS '생성일시';


--
-- Name: COLUMN code.updated_id; Type: COMMENT; Schema: common; Owner: -
--

COMMENT ON COLUMN common.code.updated_id IS '수정자 ID';


--
-- Name: COLUMN code.updated_dt; Type: COMMENT; Schema: common; Owner: -
--

COMMENT ON COLUMN common.code.updated_dt IS '수정일시';


--
-- Name: COLUMN code.order_path; Type: COMMENT; Schema: common; Owner: -
--

COMMENT ON COLUMN common.code.order_path IS '계층 정렬 순서';


--
-- Name: code_code_id_seq; Type: SEQUENCE; Schema: common; Owner: -
--

ALTER TABLE common.code ALTER COLUMN code_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME common.code_code_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: menu; Type: TABLE; Schema: common; Owner: -
--

CREATE TABLE common.menu (
    menu_id integer NOT NULL,
    menu_code character varying(50) NOT NULL,
    upper_menu_id integer,
    menu_name character varying(200) NOT NULL,
    menu_cn character varying(400),
    url character varying(300),
    srt integer,
    use_yn boolean DEFAULT true,
    created_id integer,
    created_dt timestamp with time zone DEFAULT now(),
    updated_id integer,
    updated_dt timestamp with time zone DEFAULT now()
);


--
-- Name: TABLE menu; Type: COMMENT; Schema: common; Owner: -
--

COMMENT ON TABLE common.menu IS '시스템 메뉴 관리 테이블';


--
-- Name: COLUMN menu.menu_id; Type: COMMENT; Schema: common; Owner: -
--

COMMENT ON COLUMN common.menu.menu_id IS '메뉴 PK';


--
-- Name: COLUMN menu.menu_code; Type: COMMENT; Schema: common; Owner: -
--

COMMENT ON COLUMN common.menu.menu_code IS '메뉴 코드 (논리 식별자)';


--
-- Name: COLUMN menu.upper_menu_id; Type: COMMENT; Schema: common; Owner: -
--

COMMENT ON COLUMN common.menu.upper_menu_id IS '상위 메뉴 ID';


--
-- Name: COLUMN menu.menu_name; Type: COMMENT; Schema: common; Owner: -
--

COMMENT ON COLUMN common.menu.menu_name IS '메뉴명';


--
-- Name: COLUMN menu.menu_cn; Type: COMMENT; Schema: common; Owner: -
--

COMMENT ON COLUMN common.menu.menu_cn IS '메뉴 설명';


--
-- Name: COLUMN menu.url; Type: COMMENT; Schema: common; Owner: -
--

COMMENT ON COLUMN common.menu.url IS '메뉴 URL';


--
-- Name: COLUMN menu.srt; Type: COMMENT; Schema: common; Owner: -
--

COMMENT ON COLUMN common.menu.srt IS '정렬 순서';


--
-- Name: COLUMN menu.use_yn; Type: COMMENT; Schema: common; Owner: -
--

COMMENT ON COLUMN common.menu.use_yn IS '사용 여부';


--
-- Name: COLUMN menu.created_id; Type: COMMENT; Schema: common; Owner: -
--

COMMENT ON COLUMN common.menu.created_id IS '생성자 ID';


--
-- Name: COLUMN menu.created_dt; Type: COMMENT; Schema: common; Owner: -
--

COMMENT ON COLUMN common.menu.created_dt IS '생성일시';


--
-- Name: COLUMN menu.updated_id; Type: COMMENT; Schema: common; Owner: -
--

COMMENT ON COLUMN common.menu.updated_id IS '수정자 ID';


--
-- Name: COLUMN menu.updated_dt; Type: COMMENT; Schema: common; Owner: -
--

COMMENT ON COLUMN common.menu.updated_dt IS '수정일시';


--
-- Name: menu_menu_id_seq; Type: SEQUENCE; Schema: common; Owner: -
--

ALTER TABLE common.menu ALTER COLUMN menu_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME common.menu_menu_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: menu_permission_map; Type: TABLE; Schema: common; Owner: -
--

CREATE TABLE common.menu_permission_map (
    menu_id integer NOT NULL,
    permission_id integer NOT NULL
);


--
-- Name: TABLE menu_permission_map; Type: COMMENT; Schema: common; Owner: -
--

COMMENT ON TABLE common.menu_permission_map IS '메뉴-권한 매핑 테이블';


--
-- Name: COLUMN menu_permission_map.menu_id; Type: COMMENT; Schema: common; Owner: -
--

COMMENT ON COLUMN common.menu_permission_map.menu_id IS '메뉴 PK';


--
-- Name: COLUMN menu_permission_map.permission_id; Type: COMMENT; Schema: common; Owner: -
--

COMMENT ON COLUMN common.menu_permission_map.permission_id IS '권한 PK';


--
-- Name: org; Type: TABLE; Schema: common; Owner: -
--

CREATE TABLE common.org (
    org_id integer NOT NULL,
    upper_org_id integer,
    org_name character varying(200),
    srt integer,
    use_yn boolean DEFAULT true,
    created_id integer,
    created_dt timestamp with time zone DEFAULT now(),
    updated_id integer,
    updated_dt timestamp with time zone DEFAULT now(),
    org_code character varying NOT NULL
);


--
-- Name: TABLE org; Type: COMMENT; Schema: common; Owner: -
--

COMMENT ON TABLE common.org IS '조직 관리 테이블';


--
-- Name: COLUMN org.org_id; Type: COMMENT; Schema: common; Owner: -
--

COMMENT ON COLUMN common.org.org_id IS '조직 PK';


--
-- Name: COLUMN org.upper_org_id; Type: COMMENT; Schema: common; Owner: -
--

COMMENT ON COLUMN common.org.upper_org_id IS '상위 조직 ID';


--
-- Name: COLUMN org.org_name; Type: COMMENT; Schema: common; Owner: -
--

COMMENT ON COLUMN common.org.org_name IS '조직명';


--
-- Name: COLUMN org.srt; Type: COMMENT; Schema: common; Owner: -
--

COMMENT ON COLUMN common.org.srt IS '정렬 순서';


--
-- Name: COLUMN org.use_yn; Type: COMMENT; Schema: common; Owner: -
--

COMMENT ON COLUMN common.org.use_yn IS '사용 여부';


--
-- Name: COLUMN org.created_id; Type: COMMENT; Schema: common; Owner: -
--

COMMENT ON COLUMN common.org.created_id IS '생성자 ID';


--
-- Name: COLUMN org.created_dt; Type: COMMENT; Schema: common; Owner: -
--

COMMENT ON COLUMN common.org.created_dt IS '생성일시';


--
-- Name: COLUMN org.updated_id; Type: COMMENT; Schema: common; Owner: -
--

COMMENT ON COLUMN common.org.updated_id IS '수정자 ID';


--
-- Name: COLUMN org.updated_dt; Type: COMMENT; Schema: common; Owner: -
--

COMMENT ON COLUMN common.org.updated_dt IS '수정일시';


--
-- Name: COLUMN org.org_code; Type: COMMENT; Schema: common; Owner: -
--

COMMENT ON COLUMN common.org.org_code IS '조직코드';


--
-- Name: org_org_id_seq; Type: SEQUENCE; Schema: common; Owner: -
--

ALTER TABLE common.org ALTER COLUMN org_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME common.org_org_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: permission; Type: TABLE; Schema: common; Owner: -
--

CREATE TABLE common.permission (
    permission_id integer NOT NULL,
    permission_code character varying(100) NOT NULL,
    permission_name character varying(200),
    use_yn boolean DEFAULT true,
    created_id integer,
    created_dt timestamp with time zone DEFAULT now(),
    updated_id integer,
    updated_dt timestamp with time zone DEFAULT now()
);


--
-- Name: TABLE permission; Type: COMMENT; Schema: common; Owner: -
--

COMMENT ON TABLE common.permission IS '권한 정의 테이블 (CRUD 등)';


--
-- Name: COLUMN permission.permission_id; Type: COMMENT; Schema: common; Owner: -
--

COMMENT ON COLUMN common.permission.permission_id IS '권한 PK';


--
-- Name: COLUMN permission.permission_code; Type: COMMENT; Schema: common; Owner: -
--

COMMENT ON COLUMN common.permission.permission_code IS '권한 코드 (예: USER_READ)';


--
-- Name: COLUMN permission.permission_name; Type: COMMENT; Schema: common; Owner: -
--

COMMENT ON COLUMN common.permission.permission_name IS '권한명 (설명)';


--
-- Name: COLUMN permission.use_yn; Type: COMMENT; Schema: common; Owner: -
--

COMMENT ON COLUMN common.permission.use_yn IS '사용 여부';


--
-- Name: COLUMN permission.created_id; Type: COMMENT; Schema: common; Owner: -
--

COMMENT ON COLUMN common.permission.created_id IS '생성자 ID';


--
-- Name: COLUMN permission.created_dt; Type: COMMENT; Schema: common; Owner: -
--

COMMENT ON COLUMN common.permission.created_dt IS '생성일시';


--
-- Name: COLUMN permission.updated_id; Type: COMMENT; Schema: common; Owner: -
--

COMMENT ON COLUMN common.permission.updated_id IS '수정자 ID';


--
-- Name: COLUMN permission.updated_dt; Type: COMMENT; Schema: common; Owner: -
--

COMMENT ON COLUMN common.permission.updated_dt IS '수정일시';


--
-- Name: permission_permission_id_seq; Type: SEQUENCE; Schema: common; Owner: -
--

CREATE SEQUENCE common.permission_permission_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- Name: permission_permission_id_seq; Type: SEQUENCE OWNED BY; Schema: common; Owner: -
--

ALTER SEQUENCE common.permission_permission_id_seq OWNED BY common.permission.permission_id;


--
-- Name: refresh_token; Type: TABLE; Schema: common; Owner: -
--

CREATE TABLE common.refresh_token (
    refresh_token_id bigint NOT NULL,
    token_id character varying(64) NOT NULL,
    token_hash character varying(512) NOT NULL,
    user_id bigint NOT NULL,
    expires_at timestamp with time zone NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    last_used_at timestamp with time zone,
    revoked boolean DEFAULT false NOT NULL,
    revoked_at timestamp with time zone,
    replaced_by_token_id character varying(64),
    CONSTRAINT ck_refresh_token_revocation CHECK (((revoked = false) OR (revoked_at IS NOT NULL)))
);


--
-- Name: refresh_token_refresh_token_id_seq; Type: SEQUENCE; Schema: common; Owner: -
--

CREATE SEQUENCE common.refresh_token_refresh_token_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- Name: refresh_token_refresh_token_id_seq; Type: SEQUENCE OWNED BY; Schema: common; Owner: -
--

ALTER SEQUENCE common.refresh_token_refresh_token_id_seq OWNED BY common.refresh_token.refresh_token_id;


--
-- Name: role; Type: TABLE; Schema: common; Owner: -
--

CREATE TABLE common.role (
    role_id integer NOT NULL,
    role_name character varying(200) NOT NULL,
    use_yn boolean DEFAULT true,
    created_id integer,
    created_dt timestamp with time zone DEFAULT now(),
    updated_id integer,
    updated_dt timestamp with time zone DEFAULT now()
);


--
-- Name: TABLE role; Type: COMMENT; Schema: common; Owner: -
--

COMMENT ON TABLE common.role IS '사용자 역할(권한 그룹) 테이블';


--
-- Name: COLUMN role.role_id; Type: COMMENT; Schema: common; Owner: -
--

COMMENT ON COLUMN common.role.role_id IS '역할 PK';


--
-- Name: COLUMN role.role_name; Type: COMMENT; Schema: common; Owner: -
--

COMMENT ON COLUMN common.role.role_name IS '역할명 (예: 관리자, 사용자)';


--
-- Name: COLUMN role.use_yn; Type: COMMENT; Schema: common; Owner: -
--

COMMENT ON COLUMN common.role.use_yn IS '사용 여부';


--
-- Name: COLUMN role.created_id; Type: COMMENT; Schema: common; Owner: -
--

COMMENT ON COLUMN common.role.created_id IS '생성자 ID';


--
-- Name: COLUMN role.created_dt; Type: COMMENT; Schema: common; Owner: -
--

COMMENT ON COLUMN common.role.created_dt IS '생성일시';


--
-- Name: COLUMN role.updated_id; Type: COMMENT; Schema: common; Owner: -
--

COMMENT ON COLUMN common.role.updated_id IS '수정자 ID';


--
-- Name: COLUMN role.updated_dt; Type: COMMENT; Schema: common; Owner: -
--

COMMENT ON COLUMN common.role.updated_dt IS '수정일시';


--
-- Name: role_permission_map; Type: TABLE; Schema: common; Owner: -
--

CREATE TABLE common.role_permission_map (
    role_id integer NOT NULL,
    permission_id integer NOT NULL
);


--
-- Name: TABLE role_permission_map; Type: COMMENT; Schema: common; Owner: -
--

COMMENT ON TABLE common.role_permission_map IS '역할-권한 매핑 테이블';


--
-- Name: COLUMN role_permission_map.role_id; Type: COMMENT; Schema: common; Owner: -
--

COMMENT ON COLUMN common.role_permission_map.role_id IS '역할 PK';


--
-- Name: COLUMN role_permission_map.permission_id; Type: COMMENT; Schema: common; Owner: -
--

COMMENT ON COLUMN common.role_permission_map.permission_id IS '권한 PK';


--
-- Name: role_role_id_seq; Type: SEQUENCE; Schema: common; Owner: -
--

ALTER TABLE common.role ALTER COLUMN role_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME common.role_role_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: user_role_map; Type: TABLE; Schema: common; Owner: -
--

CREATE TABLE common.user_role_map (
    user_id integer NOT NULL,
    role_id integer NOT NULL
);


--
-- Name: TABLE user_role_map; Type: COMMENT; Schema: common; Owner: -
--

COMMENT ON TABLE common.user_role_map IS '사용자-역할 매핑 테이블';


--
-- Name: COLUMN user_role_map.user_id; Type: COMMENT; Schema: common; Owner: -
--

COMMENT ON COLUMN common.user_role_map.user_id IS '사용자 PK';


--
-- Name: COLUMN user_role_map.role_id; Type: COMMENT; Schema: common; Owner: -
--

COMMENT ON COLUMN common.user_role_map.role_id IS '역할 PK';


--
-- Name: users; Type: TABLE; Schema: common; Owner: -
--

CREATE TABLE common.users (
    user_id integer NOT NULL,
    email character varying(200) NOT NULL,
    login_id character varying(100),
    user_password character varying(400),
    user_name character varying(100),
    org_id integer,
    emp_no character varying(100),
    pstn_name character varying(200),
    tel character varying(100),
    user_status_code_id integer,
    user_password_update_dt timestamp with time zone,
    user_password_fail_cnt integer,
    old1_user_password character varying(400),
    use_yn boolean DEFAULT true,
    created_id integer,
    created_dt timestamp with time zone DEFAULT now(),
    updated_id integer,
    updated_dt timestamp with time zone DEFAULT now()
);


--
-- Name: TABLE users; Type: COMMENT; Schema: common; Owner: -
--

COMMENT ON TABLE common.users IS '사용자 계정 관리 테이블';


--
-- Name: COLUMN users.user_id; Type: COMMENT; Schema: common; Owner: -
--

COMMENT ON COLUMN common.users.user_id IS '사용자 PK';


--
-- Name: COLUMN users.email; Type: COMMENT; Schema: common; Owner: -
--

COMMENT ON COLUMN common.users.email IS '이메일 (로그인 계정)';


--
-- Name: COLUMN users.login_id; Type: COMMENT; Schema: common; Owner: -
--

COMMENT ON COLUMN common.users.login_id IS '로그인 ID';


--
-- Name: COLUMN users.user_password; Type: COMMENT; Schema: common; Owner: -
--

COMMENT ON COLUMN common.users.user_password IS '비밀번호 (암호화 저장)';


--
-- Name: COLUMN users.user_name; Type: COMMENT; Schema: common; Owner: -
--

COMMENT ON COLUMN common.users.user_name IS '사용자 이름';


--
-- Name: COLUMN users.org_id; Type: COMMENT; Schema: common; Owner: -
--

COMMENT ON COLUMN common.users.org_id IS '소속 조직 ID';


--
-- Name: COLUMN users.emp_no; Type: COMMENT; Schema: common; Owner: -
--

COMMENT ON COLUMN common.users.emp_no IS '사번';


--
-- Name: COLUMN users.pstn_name; Type: COMMENT; Schema: common; Owner: -
--

COMMENT ON COLUMN common.users.pstn_name IS '직위명';


--
-- Name: COLUMN users.tel; Type: COMMENT; Schema: common; Owner: -
--

COMMENT ON COLUMN common.users.tel IS '전화번호';


--
-- Name: COLUMN users.user_status_code_id; Type: COMMENT; Schema: common; Owner: -
--

COMMENT ON COLUMN common.users.user_status_code_id IS '사용자 상태 코드 (공통코드 참조)';


--
-- Name: COLUMN users.user_password_update_dt; Type: COMMENT; Schema: common; Owner: -
--

COMMENT ON COLUMN common.users.user_password_update_dt IS '비밀번호 변경일시';


--
-- Name: COLUMN users.user_password_fail_cnt; Type: COMMENT; Schema: common; Owner: -
--

COMMENT ON COLUMN common.users.user_password_fail_cnt IS '비밀번호 실패 횟수';


--
-- Name: COLUMN users.old1_user_password; Type: COMMENT; Schema: common; Owner: -
--

COMMENT ON COLUMN common.users.old1_user_password IS '이전 비밀번호';


--
-- Name: COLUMN users.use_yn; Type: COMMENT; Schema: common; Owner: -
--

COMMENT ON COLUMN common.users.use_yn IS '사용 여부';


--
-- Name: COLUMN users.created_id; Type: COMMENT; Schema: common; Owner: -
--

COMMENT ON COLUMN common.users.created_id IS '생성자 ID';


--
-- Name: COLUMN users.created_dt; Type: COMMENT; Schema: common; Owner: -
--

COMMENT ON COLUMN common.users.created_dt IS '생성일시';


--
-- Name: COLUMN users.updated_id; Type: COMMENT; Schema: common; Owner: -
--

COMMENT ON COLUMN common.users.updated_id IS '수정자 ID';


--
-- Name: COLUMN users.updated_dt; Type: COMMENT; Schema: common; Owner: -
--

COMMENT ON COLUMN common.users.updated_dt IS '수정일시';


--
-- Name: user_user_id_seq; Type: SEQUENCE; Schema: common; Owner: -
--

ALTER TABLE common.users ALTER COLUMN user_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME common.user_user_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: permission permission_id; Type: DEFAULT; Schema: common; Owner: -
--

ALTER TABLE ONLY common.permission ALTER COLUMN permission_id SET DEFAULT nextval('common.permission_permission_id_seq'::regclass);


--
-- Name: refresh_token refresh_token_id; Type: DEFAULT; Schema: common; Owner: -
--

ALTER TABLE ONLY common.refresh_token ALTER COLUMN refresh_token_id SET DEFAULT nextval('common.refresh_token_refresh_token_id_seq'::regclass);


--
-- Name: atch_file_item atch_file_item_pkey; Type: CONSTRAINT; Schema: common; Owner: -
--

ALTER TABLE ONLY common.atch_file_item
    ADD CONSTRAINT atch_file_item_pkey PRIMARY KEY (atch_file_item_id);


--
-- Name: atch_file atch_file_pkey; Type: CONSTRAINT; Schema: common; Owner: -
--

ALTER TABLE ONLY common.atch_file
    ADD CONSTRAINT atch_file_pkey PRIMARY KEY (atch_file_id);


--
-- Name: code code_code_key; Type: CONSTRAINT; Schema: common; Owner: -
--

ALTER TABLE ONLY common.code
    ADD CONSTRAINT code_code_key UNIQUE (code);


--
-- Name: code code_pkey; Type: CONSTRAINT; Schema: common; Owner: -
--

ALTER TABLE ONLY common.code
    ADD CONSTRAINT code_pkey PRIMARY KEY (code_id);


--
-- Name: menu menu_menu_code_key; Type: CONSTRAINT; Schema: common; Owner: -
--

ALTER TABLE ONLY common.menu
    ADD CONSTRAINT menu_menu_code_key UNIQUE (menu_code);


--
-- Name: menu_permission_map menu_permission_map_pkey; Type: CONSTRAINT; Schema: common; Owner: -
--

ALTER TABLE ONLY common.menu_permission_map
    ADD CONSTRAINT menu_permission_map_pkey PRIMARY KEY (menu_id, permission_id);


--
-- Name: menu menu_pkey; Type: CONSTRAINT; Schema: common; Owner: -
--

ALTER TABLE ONLY common.menu
    ADD CONSTRAINT menu_pkey PRIMARY KEY (menu_id);


--
-- Name: org org_pkey; Type: CONSTRAINT; Schema: common; Owner: -
--

ALTER TABLE ONLY common.org
    ADD CONSTRAINT org_pkey PRIMARY KEY (org_id);


--
-- Name: org org_unique; Type: CONSTRAINT; Schema: common; Owner: -
--

ALTER TABLE ONLY common.org
    ADD CONSTRAINT org_unique UNIQUE (org_code);


--
-- Name: permission permission_permission_code_key; Type: CONSTRAINT; Schema: common; Owner: -
--

ALTER TABLE ONLY common.permission
    ADD CONSTRAINT permission_permission_code_key UNIQUE (permission_code);


--
-- Name: permission permission_pkey; Type: CONSTRAINT; Schema: common; Owner: -
--

ALTER TABLE ONLY common.permission
    ADD CONSTRAINT permission_pkey PRIMARY KEY (permission_id);


--
-- Name: refresh_token refresh_token_pkey; Type: CONSTRAINT; Schema: common; Owner: -
--

ALTER TABLE ONLY common.refresh_token
    ADD CONSTRAINT refresh_token_pkey PRIMARY KEY (refresh_token_id);


--
-- Name: role_permission_map role_permission_map_pkey; Type: CONSTRAINT; Schema: common; Owner: -
--

ALTER TABLE ONLY common.role_permission_map
    ADD CONSTRAINT role_permission_map_pkey PRIMARY KEY (role_id, permission_id);


--
-- Name: role role_pkey; Type: CONSTRAINT; Schema: common; Owner: -
--

ALTER TABLE ONLY common.role
    ADD CONSTRAINT role_pkey PRIMARY KEY (role_id);


--
-- Name: role role_role_name_key; Type: CONSTRAINT; Schema: common; Owner: -
--

ALTER TABLE ONLY common.role
    ADD CONSTRAINT role_role_name_key UNIQUE (role_name);


--
-- Name: refresh_token uq_refresh_token_token_id; Type: CONSTRAINT; Schema: common; Owner: -
--

ALTER TABLE ONLY common.refresh_token
    ADD CONSTRAINT uq_refresh_token_token_id UNIQUE (token_id);


--
-- Name: users user_email_key; Type: CONSTRAINT; Schema: common; Owner: -
--

ALTER TABLE ONLY common.users
    ADD CONSTRAINT user_email_key UNIQUE (email);


--
-- Name: users user_pkey; Type: CONSTRAINT; Schema: common; Owner: -
--

ALTER TABLE ONLY common.users
    ADD CONSTRAINT user_pkey PRIMARY KEY (user_id);


--
-- Name: user_role_map user_role_map_pkey; Type: CONSTRAINT; Schema: common; Owner: -
--

ALTER TABLE ONLY common.user_role_map
    ADD CONSTRAINT user_role_map_pkey PRIMARY KEY (user_id, role_id);


--
-- Name: code_upper_code_id_code_idx; Type: INDEX; Schema: common; Owner: -
--

CREATE UNIQUE INDEX code_upper_code_id_code_idx ON common.code USING btree (upper_code_id, code);


--
-- Name: idx_refresh_token_user_active; Type: INDEX; Schema: common; Owner: -
--

CREATE INDEX idx_refresh_token_user_active ON common.refresh_token USING btree (user_id) WHERE (revoked = false);


--
-- Name: idx_refresh_token_user_id; Type: INDEX; Schema: common; Owner: -
--

CREATE INDEX idx_refresh_token_user_id ON common.refresh_token USING btree (user_id);


--
-- Name: atch_file atch_file_file_grp_code_id_fkey; Type: FK CONSTRAINT; Schema: common; Owner: -
--

ALTER TABLE ONLY common.atch_file
    ADD CONSTRAINT atch_file_file_grp_code_id_fkey FOREIGN KEY (file_grp_code_id) REFERENCES common.code(code_id);


--
-- Name: atch_file_item atch_file_item_atch_file_id_fkey; Type: FK CONSTRAINT; Schema: common; Owner: -
--

ALTER TABLE ONLY common.atch_file_item
    ADD CONSTRAINT atch_file_item_atch_file_id_fkey FOREIGN KEY (atch_file_id) REFERENCES common.atch_file(atch_file_id);


--
-- Name: code code_upper_code_id_fkey; Type: FK CONSTRAINT; Schema: common; Owner: -
--

ALTER TABLE ONLY common.code
    ADD CONSTRAINT code_upper_code_id_fkey FOREIGN KEY (upper_code_id) REFERENCES common.code(code_id);


--
-- Name: refresh_token fk_refresh_token_replace; Type: FK CONSTRAINT; Schema: common; Owner: -
--

ALTER TABLE ONLY common.refresh_token
    ADD CONSTRAINT fk_refresh_token_replace FOREIGN KEY (replaced_by_token_id) REFERENCES common.refresh_token(token_id);


--
-- Name: refresh_token fk_refresh_token_user; Type: FK CONSTRAINT; Schema: common; Owner: -
--

ALTER TABLE ONLY common.refresh_token
    ADD CONSTRAINT fk_refresh_token_user FOREIGN KEY (user_id) REFERENCES common.users(user_id) ON DELETE CASCADE;


--
-- Name: menu_permission_map menu_permission_map_menu_id_fkey; Type: FK CONSTRAINT; Schema: common; Owner: -
--

ALTER TABLE ONLY common.menu_permission_map
    ADD CONSTRAINT menu_permission_map_menu_id_fkey FOREIGN KEY (menu_id) REFERENCES common.menu(menu_id);


--
-- Name: menu_permission_map menu_permission_map_permission_id_fkey; Type: FK CONSTRAINT; Schema: common; Owner: -
--

ALTER TABLE ONLY common.menu_permission_map
    ADD CONSTRAINT menu_permission_map_permission_id_fkey FOREIGN KEY (permission_id) REFERENCES common.permission(permission_id);


--
-- Name: menu menu_upper_menu_id_fkey; Type: FK CONSTRAINT; Schema: common; Owner: -
--

ALTER TABLE ONLY common.menu
    ADD CONSTRAINT menu_upper_menu_id_fkey FOREIGN KEY (upper_menu_id) REFERENCES common.menu(menu_id);


--
-- Name: org org_upper_org_id_fkey; Type: FK CONSTRAINT; Schema: common; Owner: -
--

ALTER TABLE ONLY common.org
    ADD CONSTRAINT org_upper_org_id_fkey FOREIGN KEY (upper_org_id) REFERENCES common.org(org_id);


--
-- Name: role_permission_map role_permission_map_permission_id_fkey; Type: FK CONSTRAINT; Schema: common; Owner: -
--

ALTER TABLE ONLY common.role_permission_map
    ADD CONSTRAINT role_permission_map_permission_id_fkey FOREIGN KEY (permission_id) REFERENCES common.permission(permission_id);


--
-- Name: role_permission_map role_permission_map_role_id_fkey; Type: FK CONSTRAINT; Schema: common; Owner: -
--

ALTER TABLE ONLY common.role_permission_map
    ADD CONSTRAINT role_permission_map_role_id_fkey FOREIGN KEY (role_id) REFERENCES common.role(role_id);


--
-- Name: users user_org_id_fkey; Type: FK CONSTRAINT; Schema: common; Owner: -
--

ALTER TABLE ONLY common.users
    ADD CONSTRAINT user_org_id_fkey FOREIGN KEY (org_id) REFERENCES common.org(org_id);


--
-- Name: user_role_map user_role_map_role_id_fkey; Type: FK CONSTRAINT; Schema: common; Owner: -
--

ALTER TABLE ONLY common.user_role_map
    ADD CONSTRAINT user_role_map_role_id_fkey FOREIGN KEY (role_id) REFERENCES common.role(role_id);


--
-- Name: user_role_map user_role_map_user_id_fkey; Type: FK CONSTRAINT; Schema: common; Owner: -
--

ALTER TABLE ONLY common.user_role_map
    ADD CONSTRAINT user_role_map_user_id_fkey FOREIGN KEY (user_id) REFERENCES common.users(user_id);


--
-- Name: users user_user_status_code_id_fkey; Type: FK CONSTRAINT; Schema: common; Owner: -
--

ALTER TABLE ONLY common.users
    ADD CONSTRAINT user_user_status_code_id_fkey FOREIGN KEY (user_status_code_id) REFERENCES common.code(code_id);


--
-- PostgreSQL database dump complete
--

\unrestrict 1vy5UC3Vcvz5wV9C3j4FNb4Lya5g3v9ZCmJpchARn59NfYtHlZjH1qSE1Kf7Kfc

